# This workflow will build a golang project

name: Windows CI

on:
  push:
    branches: [ "windows-tests" ]

  pull_request:
    branches: [ "windows-tests" ]

  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:

  run-tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # necessary for testing proxy/Process swapping
    - name: Create simple-responder
      shell: bash
      run: make simple-responder

    - name: Test all
      shell: bash
      run: make test-all